---
deployment:
  tasks:
    # Deploy aplicația în subdirectory
    - export APPPATH=/home/rbcjgzba/public_html/document-archive/
    - /bin/mkdir -p $APPPATH
    
    # Copy toate fișierele aplicației
    - /bin/cp -R * $APPPATH/
    - /bin/cp -R .[^.]* $APPPATH/ 2>/dev/null || true
    
    # Setează Document Root către public/ 
    - export PUBLICPATH=/home/rbcjgzba/public_html/public_gusturidelatara/
    - /bin/mkdir -p $PUBLICPATH
    - /bin/cp -R $APPPATH/public/* $PUBLICPATH/
    
    # Actualizează căile în index.php
    - /bin/sed -i "s|require_once '../config/config.php'|require_once '/home/rbcjgzba/public_html/document-archive/config/config.php'|g" $PUBLICPATH/index.php
    - /bin/sed -i "s|require_once '../includes/|require_once '/home/rbcjgzba/public_html/document-archive/includes/|g" $PUBLICPATH/*.php
    
    # Setează permisiuni
    - /bin/chmod -R 755 $APPPATH/storage/
    - /bin/chmod -R 644 $APPPATH/config/
    - /bin/chmod 755 $PUBLICPATH/
    
    # Activează production config
    - /bin/cp $APPPATH/config/config.production.php $APPPATH/config/config.local.php